<?php
/**
 * Created by PhpStorm.
 * User: tony
 * Date: 3/23/19
 * Time: 10:20 PM
 */

/**
 * Implements hook_menu().
 */
function d8_custom_page_menu() {
  $items['foo'] = [
    'page callback' => 'd8_custom_page_foo',
    'access arguments' => [ 'access content' ]
  ];
  return $items;
}

function d8_custom_page_foo() {
  return "<h1>bar</h1>";
}

function d8_custom_page_bar() {
  return "<h2>foo</h2>";
}