pipeline:
  build:
    image: t2/d7-apache
    depends_on:
      - maria-server
    commands:
      - composer install
      - cd web && ../vendor/bin/drush cc all

services:
  maria-server:
    image: mariadb:latest
    container_name: d7-mariadb
    environment:
      MYSQL_DATABASE:  drupal
      MYSQL_ROOT_PASSWORD: drupal
    restart: always

volumes:
  mysqldata
