pipeline:
  build:
    image: tonetaylor/d7-apache
    commands:
      - sleep 20
      - composer install
      - cd web
      - ../vendor/bin/drush si standard \
        --db-url=mysql://maria-server:3306/drupal --yes
      - ../vendor/bin/drush en d8_custom_page --yes
      - cd .. && vendor/bin/phpunit

services:
  maria-server:
    image: mariadb:latest
    container_name: d7-mariadb
    environment:
      MYSQL_DATABASE:  drupal
      MYSQL_ROOT_PASSWORD: drupal
    restart: always

